### ISSUE TITLE
go tool pprof demo

### ISSUE THREAD

**Issue by Lancerio** [g0hacker/go_command_tutorial#26]
Firstly,i was run in go1.71
code list:
`func GetSrcDirs(fresh bool) []string {
	if len(srcDirsCache) > 0 && !fresh {
		return srcDirsCache
	}
	gorootSrcDir := filepath.Join(GetGoroot(), "src", "pkg")

	gopaths := GetAllGopath()
	gopathSrcDirs := make([]string, len(gopaths))
	for i, v := range gopaths {
		gopathSrcDirs[i] = filepath.Join(v, "src")
	}
	srcDirs := make([]string, 0)
	srcDirs = append(srcDirs, gorootSrcDir)
	srcDirs = append(srcDirs, gopathSrcDirs...)
	srcDirsCache = make([]string, len(srcDirs))
	copy(srcDirsCache, srcDirs)
	return srcDirs
}`
this function which path is "goc2p/src/pkg/tool" in goc2p project.and the gorootSrcDir := filepath.Join(GetRoot(), "src", "pkg") has a little problem,I think it may be gorootSrcDir := filepath.Join(GetRoot(), "src")

**Comment by g0hacker** [comment]
In Go 1.3 & Go 1.4, the source of standard libarary is located in $GOROOT/src/pkg.
